---
title: "Proposal"
output: github_document
---

Due to the pandemic, people are required to wear face covering. It seems like there are less people smoking in the public because of the face mask in NYC. How did the smoking rate change in recent years? What are the smoking trends in NYC and across the U.S.? To answer these questions, our group members : Ke Xu (kx2173), Lesi He(lh3109), Tsang Sze Pui (st3340), Wanxin Qi (wq2161), Ziyue Yang (zy2378) hopes to investigate smoking issues among different groups such as age, gender, race, in New York city in the past 10 years. This project, “Smoking in the U.S.”, may contain plots that display a map showing smoking behaviors in different areas in the U.S., a comparison between cigarette consumption between NY and other states in the U.S., and a generalisation of the general tobacco consumption in the U.S. over the past 10 years. Our anticipated data source includes BRFSS Questionnaires dataset form CDC, Licensed Wholesale Cigarette Dealers from NYC OpenData, National Survey on Drug Use and Health(NSDUH) from Substance Abuse & Mental Health Data Archive(SAMHDA). When working on this project, we need to overcome several coding challenges. As each dataset provides a limited picture of the information, we need to combine multiple datasets in order to draw the conclusion from a more macroscopic and prospective level. The time and information of the datasets may not match, some data manipulation such as filtering the date and location may be needed in order to combine the dataset in an organised way. We plan to have a group meeting by Nov. 19, and read related readings about our study, and clean our data set. By the end of November, we plan to complete most of our data analysis and have a mid-term group meeting, discussing report writing and website making. Starting from December, we plan to use these ten days to write and refine the report, and make our websites. We plan to have several meetings if necessary. 